spring:
  application:
    name: springboot-prometheus1122
  servlet:
      multipart:
        max-file-size: 50MB
        max-request-size: 50MB
        enabled: true
server:
  port: 8202


management:
  endpoints:
    web:
      exposure:
        include:  '*'
      base-path: /actuator
  metrics:
    tags:
      application: ${spring.application.name}